"""Phase 3: discovery foundation (jobs, schemas, datasets, columns, dataset_key_columns)

Revision ID: 0007_phase3_discovery_foundation
Revises: 0006_seed_roles_and_permissions
Create Date: 2026-08-19

Creates, exactly per the frozen Database Design v2 field lists:
  - jobs
  - schemas
  - datasets (including key_strategy)
  - columns
  - dataset_key_columns

Plus the two explicitly authorized additive amendments for this phase:
  (a) jobs.job_type's CHECK constraint includes 'DISCOVERY_RUN' alongside
      the existing PROFILE_RUN, VALIDATION_RUN, STAGING_BUILD, PUBLISH,
      EXPORT values.
  (b) columns.is_active BOOLEAN NOT NULL DEFAULT true, matching the same
      pattern already present on schemas/datasets/connections/data_sources.

One deliberate, necessary deviation from the literal frozen field list,
not an unauthorized schema change: columns.semantic_category_ai_suggestion_id
is created as a plain nullable UUID column WITHOUT its documented FK to
ai_suggestions(id), because the ai_suggestions table does not exist until
a later (AI) phase. The column and its CHECK constraints are created
exactly as designed; only the FK constraint is deferred, and will be added
in the migration that creates ai_suggestions. No column, index, or CHECK
value beyond what is listed above is created by this migration.

Hand-written rather than autogenerated, matching Phase 2's discipline: the
job_type/status/object_type/key_strategy/normalized_data_type CHECK
constraints are Postgres-specific and easy for --autogenerate to omit or
get wrong, so they are spelled out explicitly here and were hand-verified
against the frozen Database Design v2 before this migration was applied.

Also seeds three new permission codes: discovery.run, metadata.read,
metadata.manage, and links them into every one of the 5 roles seeded by
migration 0006 (administrator, analyst, reviewer, approver, publisher).

This is the first phase where the frozen Backend Technical Design's role
hierarchy (reviewer approx-equals analyst; approver is a superset of
analyst; publisher is a superset of approver, which is a superset of
analyst) is fully instantiated for a new permission domain: all three new
permission codes are added to every role's grant set, not just
administrator/analyst. This is NOT because that matrix was "already
established" in Phase 2 — migration 0006 deliberately left
reviewer/approver/publisher with zero permissions, simply because none of
Phase 2's 7 permission codes (users.*, connections.*, data_sources.*,
audit.read) were relevant to those roles yet. It was not a policy that
those roles remain permission-less; discovery/metadata permissions are the
first domain where their place in the role hierarchy actually applies, so
this migration is where they receive their first grants.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0007_phase3_discovery_foundation"
down_revision: Union[str, Sequence[str], None] = "0006_seed_roles_and_permissions"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSIONS = [
    ("discovery.run", "discovery"),
    ("metadata.read", "metadata"),
    ("metadata.manage", "metadata"),
]

# Per the frozen Backend Technical Design's role hierarchy: reviewer approx
# analyst; approver superset-of analyst; publisher superset-of approver
# superset-of analyst. All five roles receive all three new permissions.
ROLE_NAMES_RECEIVING_NEW_PERMISSIONS = ["administrator", "analyst", "reviewer", "approver", "publisher"]


def upgrade() -> None:
    # --- jobs -----------------------------------------------------------
    op.create_table(
        "jobs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("job_type", sa.String(30), nullable=False),
        sa.Column("entity_type", sa.String(30), nullable=False),
        sa.Column("entity_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("status", sa.String(15), nullable=False, server_default="QUEUED"),
        sa.Column("progress_percentage", sa.SmallInteger(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("queued_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "job_type IN ('PROFILE_RUN', 'VALIDATION_RUN', 'STAGING_BUILD', 'PUBLISH', 'EXPORT', 'DISCOVERY_RUN')",
            name="ck_jobs_job_type",
        ),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')", name="ck_jobs_status"
        ),
    )
    op.create_index("idx_jobs_entity", "jobs", ["entity_type", "entity_id"])
    op.create_index("idx_jobs_status", "jobs", ["status"])
    op.create_index("idx_jobs_job_type_status", "jobs", ["job_type", "status"])

    # --- schemas ----------------------------------------------------------
    op.create_table(
        "schemas",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("connection_id", pg.UUID(as_uuid=True), sa.ForeignKey("connections.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("connection_id", "name", name="uq_schemas_connection_id_name"),
    )
    op.create_index("idx_schemas_connection_id", "schemas", ["connection_id"])

    # --- datasets -----------------------------------------------------------
    op.create_table(
        "datasets",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("schema_id", pg.UUID(as_uuid=True), sa.ForeignKey("schemas.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("object_type", sa.String(20), nullable=False, server_default="TABLE"),
        sa.Column("key_strategy", sa.String(20), nullable=False, server_default="ROW_INDEX_FALLBACK"),
        sa.Column("row_count_estimate", sa.BigInteger(), nullable=True),
        sa.Column("column_count", sa.Integer(), nullable=True),
        sa.Column("last_profiled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_quality_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("schema_id", "name", name="uq_datasets_schema_id_name"),
        sa.CheckConstraint("object_type IN ('TABLE', 'VIEW')", name="ck_datasets_object_type"),
        sa.CheckConstraint(
            "key_strategy IN ('SINGLE_COLUMN', 'COMPOSITE', 'ROW_INDEX_FALLBACK')",
            name="ck_datasets_key_strategy",
        ),
    )
    op.create_index("idx_datasets_schema_id", "datasets", ["schema_id"])
    op.create_index("idx_datasets_last_quality_score", "datasets", ["last_quality_score"])

    # --- columns ------------------------------------------------------------
    op.create_table(
        "columns",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("ordinal_position", sa.Integer(), nullable=False),
        sa.Column("native_data_type", sa.String(100), nullable=True),
        sa.Column("normalized_data_type", sa.String(20), nullable=False, server_default="STRING"),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("numeric_precision", sa.Integer(), nullable=True),
        sa.Column("numeric_scale", sa.Integer(), nullable=True),
        sa.Column("is_nullable", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.Column("is_primary_key", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("semantic_category", sa.String(50), nullable=True),
        sa.Column("semantic_category_source", sa.String(20), nullable=True),
        # No FK to ai_suggestions(id): that table does not exist until the AI phase.
        # See module docstring above.
        sa.Column("semantic_category_ai_suggestion_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("semantic_confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        # Amendment (b): columns.is_active, matching schemas/datasets/connections/data_sources.
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        sa.UniqueConstraint("dataset_id", "name", name="uq_columns_dataset_id_name"),
        sa.CheckConstraint(
            "normalized_data_type IN ('STRING', 'TEXT', 'INTEGER', 'DECIMAL', 'DATE', 'DATETIME', 'BOOLEAN')",
            name="ck_columns_normalized_data_type",
        ),
        sa.CheckConstraint(
            "semantic_category_source IS NULL OR semantic_category_source IN ('RULE_BASED', 'AI', 'HUMAN')",
            name="ck_columns_semantic_category_source",
        ),
        sa.CheckConstraint(
            "semantic_category_source IS NOT NULL OR semantic_category IS NULL",
            name="ck_columns_semantic_category_requires_source",
        ),
        sa.CheckConstraint(
            "(semantic_category_source = 'AI') = (semantic_category_ai_suggestion_id IS NOT NULL)",
            name="ck_columns_semantic_category_ai_suggestion_id",
        ),
    )
    op.create_index("idx_columns_dataset_id", "columns", ["dataset_id"])
    op.create_index("idx_columns_semantic_category", "columns", ["semantic_category"])
    op.create_index(
        "idx_columns_semantic_category_ai_suggestion_id", "columns", ["semantic_category_ai_suggestion_id"]
    )

    # --- dataset_key_columns --------------------------------------------------
    op.create_table(
        "dataset_key_columns",
        sa.Column(
            "dataset_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("datasets.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column(
            "column_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("columns.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("dataset_id", "ordinal", name="uq_dataset_key_columns_dataset_id_ordinal"),
    )

    # --- seed the 3 new permissions and link into the existing role matrix ----
    connection = op.get_bind()

    permission_ids: dict[str, str] = {}
    for code, category in PERMISSIONS:
        result = connection.execute(
            table("permissions", column("code", String), column("category", String))
            .insert()
            .values(code=code, category=category)
            .returning(column("id"))
        )
        permission_ids[code] = result.scalar_one()

    role_ids = {
        name: connection.execute(
            sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}
        ).scalar_one()
        for name in ROLE_NAMES_RECEIVING_NEW_PERMISSIONS
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    rows = [
        {"role_id": role_ids[role_name], "permission_id": permission_id}
        for role_name in ROLE_NAMES_RECEIVING_NEW_PERMISSIONS
        for permission_id in permission_ids.values()
    ]
    op.bulk_insert(role_permissions_table, rows)


def downgrade() -> None:
    connection = op.get_bind()

    permission_codes = tuple(code for code, _ in PERMISSIONS)
    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = ANY(:codes))"
        ),
        {"codes": list(permission_codes)},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": list(permission_codes)})

    op.drop_table("dataset_key_columns")

    op.drop_index("idx_columns_semantic_category_ai_suggestion_id", table_name="columns")
    op.drop_index("idx_columns_semantic_category", table_name="columns")
    op.drop_index("idx_columns_dataset_id", table_name="columns")
    op.drop_table("columns")

    op.drop_index("idx_datasets_last_quality_score", table_name="datasets")
    op.drop_index("idx_datasets_schema_id", table_name="datasets")
    op.drop_table("datasets")

    op.drop_index("idx_schemas_connection_id", table_name="schemas")
    op.drop_table("schemas")

    op.drop_index("idx_jobs_job_type_status", table_name="jobs")
    op.drop_index("idx_jobs_status", table_name="jobs")
    op.drop_index("idx_jobs_entity", table_name="jobs")
    op.drop_table("jobs")
