"""Phase 4: profiling foundation (profile_runs, column_profiles)

Revision ID: 0008_phase4_profiling_foundation
Revises: 0007_phase3_discovery_foundation
Create Date: 2026-08-20

Creates, exactly per the frozen Database Design v2 field lists:
  - profile_runs
  - column_profiles

Plus the two explicitly authorized additive amendments for this phase:
  (c) profile_runs.status's CHECK constraint gains 'CANCELLED' alongside
      the existing QUEUED, RUNNING, COMPLETED, FAILED values.
  (d) column_profiles gains stddev_value NUMERIC NULL and sum_value
      NUMERIC NULL.

No change to jobs.job_type: 'PROFILE_RUN' has been a valid value since the
original frozen Database Design v2 draft (Phase 3's migration 0007 amended
job_type only to add 'DISCOVERY_RUN'). No other schema change is made here.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0007: profile_runs.status and column_profiles' JSONB/
NUMERIC columns are exactly the kind of detail --autogenerate tends to
mis-render, so every column/constraint below was checked against the frozen
field list before this migration was applied.

Also seeds one new permission code, profiling.run (category: profiling),
and links it into every one of the 5 roles seeded by migration 0006. This
is not a new precedent — it follows the exact same reasoning Phase 3's
migration 0007 already established for discovery.run/metadata.read/
metadata.manage: the frozen Backend Technical Design's role hierarchy
(reviewer approximately equals analyst; approver is a superset of analyst;
publisher is a superset of approver, which is a superset of analyst) means
every role that already inherited Phase 3's permissions the same way also
inherits this one. administrator receives it too, consistent with already
having every permission.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0008_phase4_profiling_foundation"
down_revision: Union[str, Sequence[str], None] = "0007_phase3_discovery_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSION_CODE = "profiling.run"
PERMISSION_CATEGORY = "profiling"

# Same 5 roles, same reasoning, as Phase 3's migration 0007.
ROLE_NAMES_RECEIVING_NEW_PERMISSION = ["administrator", "analyst", "reviewer", "approver", "publisher"]


def upgrade() -> None:
    # --- profile_runs ---------------------------------------------------
    op.create_table(
        "profile_runs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("job_id", pg.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="QUEUED"),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("row_count", sa.BigInteger(), nullable=True),
        sa.Column("quality_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("null_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("duplicate_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("triggered_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint(
            "status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name="ck_profile_runs_status",
        ),
    )
    op.create_index(
        "idx_profile_runs_dataset_id_created_at", "profile_runs", ["dataset_id", sa.text("created_at DESC")]
    )

    # --- column_profiles --------------------------------------------------
    op.create_table(
        "column_profiles",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "profile_run_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("profile_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("column_id", pg.UUID(as_uuid=True), sa.ForeignKey("columns.id"), nullable=False),
        sa.Column("null_count", sa.BigInteger(), nullable=True),
        sa.Column("null_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("distinct_count", sa.BigInteger(), nullable=True),
        sa.Column("distinct_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("duplicate_count", sa.BigInteger(), nullable=True),
        sa.Column("duplicate_percentage", sa.Numeric(5, 2), nullable=True),
        sa.Column("min_value", sa.Text(), nullable=True),
        sa.Column("max_value", sa.Text(), nullable=True),
        sa.Column("mean_value", sa.Numeric(), nullable=True),
        sa.Column("median_value", sa.Numeric(), nullable=True),
        sa.Column("mode_value", sa.Text(), nullable=True),
        sa.Column("min_length", sa.Integer(), nullable=True),
        sa.Column("max_length", sa.Integer(), nullable=True),
        sa.Column("avg_length", sa.Numeric(6, 2), nullable=True),
        sa.Column("outlier_count", sa.BigInteger(), nullable=True),
        sa.Column("pattern_summary", pg.JSONB(), nullable=True),
        sa.Column("value_distribution", pg.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        # Amendment (d), approved for Phase 4.
        sa.Column("stddev_value", sa.Numeric(), nullable=True),
        sa.Column("sum_value", sa.Numeric(), nullable=True),
        sa.UniqueConstraint("profile_run_id", "column_id", name="uq_column_profiles_profile_run_id_column_id"),
    )
    op.create_index("idx_column_profiles_column_id", "column_profiles", ["column_id"])

    # --- seed profiling.run and link into every role -----------------------
    connection = op.get_bind()

    permission_id = connection.execute(
        table("permissions", column("code", String), column("category", String))
        .insert()
        .values(code=PERMISSION_CODE, category=PERMISSION_CATEGORY)
        .returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLE_NAMES_RECEIVING_NEW_PERMISSION
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_id, "permission_id": permission_id} for role_id in role_ids.values()],
    )


def downgrade() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = :code)"
        ),
        {"code": PERMISSION_CODE},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = :code"), {"code": PERMISSION_CODE})

    op.drop_index("idx_column_profiles_column_id", table_name="column_profiles")
    op.drop_table("column_profiles")

    op.drop_index("idx_profile_runs_dataset_id_created_at", table_name="profile_runs")
    op.drop_table("profile_runs")
