"""Phase 5: validation foundation (Rule Catalog + Validation, 9 tables)

Revision ID: 0009_phase5_validation_base
Revises: 0008_phase4_profiling_foundation
Create Date: 2026-08-21

Note on the revision id: "0009_phase5_validation_foundation" (following the
naming pattern of 0007/0008 exactly) is 33 characters — one over the 32-char
limit of alembic_version.version_num (VARCHAR(32), Alembic's own default
table, not part of the frozen Database Design v2). Discovered when the
upgrade failed at the final `UPDATE alembic_version` step (the DDL itself
had already succeeded inside the same transaction and rolled back cleanly
with it). Shortened to "...validation_base" to fit.

Creates, exactly per the frozen Database Design v2 field lists (Sections 4
RULES and 5 VALIDATION):
  - rules
  - rule_versions
  - validation_templates
  - rule_assignments  (with the 3 CHECK constraints + 6 scope-aware partial
    unique indexes replacing the old ambiguous single UNIQUE constraint)
  - rule_assignment_columns
  - validation_runs   (status CHECK includes CREATED, per the frozen design
    — validation_runs' state machine starts one state earlier than
    profile_runs')
  - validation_results (includes source_row_hash, the cross-stage fingerprint
    a future Staging phase will compare against)
  - validation_failures
  - validation_metrics

No change to jobs.job_type or jobs.status: 'VALIDATION_RUN' and 'CANCELLED'
have both been valid values since migration 0007 (confirmed by reading that
migration's literal CHECK-constraint text before writing this one) — no
existing table is altered by this migration.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0008: the CHECK constraints and 6 partial unique indexes on
rule_assignments are exactly the kind of detail --autogenerate mis-renders.

Also seeds one new permission code, validation.run (category: validation),
and links it into every one of the 5 roles seeded by migration 0006 —
same reasoning as migrations 0007 (discovery.run/metadata.*) and 0008
(profiling.run): the frozen role hierarchy (reviewer approximately equals
analyst; approver is a superset of analyst; publisher is a superset of
approver, which is a superset of analyst) means every role that already
inherited those permissions also inherits this one. administrator receives
it too, consistent with already having every permission.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0009_phase5_validation_base"
down_revision: Union[str, Sequence[str], None] = "0008_phase4_profiling_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSION_CODE = "validation.run"
PERMISSION_CATEGORY = "validation"

# Same 5 roles, same reasoning, as Phase 3's migration 0007 and Phase 4's migration 0008.
ROLE_NAMES_RECEIVING_NEW_PERMISSION = ["administrator", "analyst", "reviewer", "approver", "publisher"]


def upgrade() -> None:
    # --- rules ------------------------------------------------------------
    op.create_table(
        "rules",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category", sa.String(100), nullable=True),
        sa.Column("rule_type", sa.String(50), nullable=False),
        sa.Column("origin", sa.String(20), nullable=False, server_default="BUILT_IN"),
        sa.Column("status", sa.String(20), nullable=False, server_default="ACTIVE"),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("name", name="uq_rules_name"),
        sa.CheckConstraint("origin IN ('BUILT_IN', 'CUSTOM', 'AI_RECOMMENDED')", name="ck_rules_origin"),
        sa.CheckConstraint("status IN ('ACTIVE', 'DISABLED', 'PENDING_REVIEW')", name="ck_rules_status"),
        # rule_type deliberately has NO CHECK constraint: the frozen design doc
        # lists it as VARCHAR(50) NOT NULL with no enumerated Notes value list
        # (unlike origin/status above), so the six-rule-type restriction
        # approved for Phase 5 (COMPLETENESS, UNIQUENESS, DUPLICATE, RANGE,
        # PATTERN, CROSS_COLUMN) is enforced at the RulesService layer only —
        # adding a DB CHECK here would be inventing a schema constraint the
        # frozen design does not specify.
    )
    op.create_index("idx_rules_status", "rules", ["status"])
    op.create_index("idx_rules_origin", "rules", ["origin"])

    # --- rule_versions ------------------------------------------------------
    op.create_table(
        "rule_versions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("rule_id", pg.UUID(as_uuid=True), sa.ForeignKey("rules.id"), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("definition", pg.JSONB(), nullable=False),
        sa.Column("severity", sa.String(20), nullable=False, server_default="MEDIUM"),
        sa.Column("error_message_template", sa.Text(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("rule_id", "version_number", name="uq_rule_versions_rule_id_version_number"),
        sa.CheckConstraint("severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name="ck_rule_versions_severity"),
    )
    op.create_index("idx_rule_versions_rule_id", "rule_versions", ["rule_id"])
    op.create_index(
        "uq_rule_versions_current",
        "rule_versions",
        ["rule_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )

    # --- validation_templates ------------------------------------------------
    op.create_table(
        "validation_templates",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        # FK to validation_runs added after that table is created below.
        sa.Column("last_run_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("last_quality_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("dataset_id", "name", name="uq_validation_templates_dataset_id_name"),
    )

    # --- rule_assignments -----------------------------------------------------
    op.create_table(
        "rule_assignments",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("rule_version_id", pg.UUID(as_uuid=True), sa.ForeignKey("rule_versions.id"), nullable=False),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("assignment_scope", sa.String(20), nullable=False),
        sa.Column("column_id", pg.UUID(as_uuid=True), sa.ForeignKey("columns.id"), nullable=True),
        sa.Column("cross_column_key", sa.Text(), nullable=True),
        sa.Column("template_id", pg.UUID(as_uuid=True), sa.ForeignKey("validation_templates.id"), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("assigned_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "assignment_scope IN ('SINGLE_COLUMN', 'DATASET_LEVEL', 'CROSS_COLUMN')",
            name="ck_rule_assignments_scope_value",
        ),
        sa.CheckConstraint(
            "(assignment_scope <> 'SINGLE_COLUMN') OR (column_id IS NOT NULL AND cross_column_key IS NULL)",
            name="ck_rule_assignments_single_column_shape",
        ),
        sa.CheckConstraint(
            "(assignment_scope <> 'DATASET_LEVEL') OR (column_id IS NULL AND cross_column_key IS NULL)",
            name="ck_rule_assignments_dataset_level_shape",
        ),
        sa.CheckConstraint(
            "(assignment_scope <> 'CROSS_COLUMN') OR (column_id IS NULL AND cross_column_key IS NOT NULL)",
            name="ck_rule_assignments_cross_column_shape",
        ),
    )
    # 6 scope-aware partial unique indexes — replaces the old ambiguous
    # single UNIQUE(rule_version_id, dataset_id, column_id, template_id).
    op.create_index(
        "uq_rule_assignments_single_no_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id", "column_id"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'SINGLE_COLUMN' AND template_id IS NULL"),
    )
    op.create_index(
        "uq_rule_assignments_single_with_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id", "column_id", "template_id"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'SINGLE_COLUMN' AND template_id IS NOT NULL"),
    )
    op.create_index(
        "uq_rule_assignments_dataset_no_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'DATASET_LEVEL' AND template_id IS NULL"),
    )
    op.create_index(
        "uq_rule_assignments_dataset_with_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id", "template_id"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'DATASET_LEVEL' AND template_id IS NOT NULL"),
    )
    op.create_index(
        "uq_rule_assignments_cross_no_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id", "cross_column_key"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'CROSS_COLUMN' AND template_id IS NULL"),
    )
    op.create_index(
        "uq_rule_assignments_cross_with_template",
        "rule_assignments",
        ["rule_version_id", "dataset_id", "cross_column_key", "template_id"],
        unique=True,
        postgresql_where=sa.text("assignment_scope = 'CROSS_COLUMN' AND template_id IS NOT NULL"),
    )
    op.create_index(
        "idx_rule_assignments_dataset_id",
        "rule_assignments",
        ["dataset_id"],
        postgresql_where=sa.text("is_enabled"),
    )
    op.create_index("idx_rule_assignments_template_id", "rule_assignments", ["template_id"])
    op.create_index("idx_rule_assignments_scope", "rule_assignments", ["assignment_scope"])

    # --- rule_assignment_columns -----------------------------------------------
    op.create_table(
        "rule_assignment_columns",
        sa.Column(
            "rule_assignment_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("rule_assignments.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("column_id", pg.UUID(as_uuid=True), sa.ForeignKey("columns.id"), primary_key=True),
        sa.Column("ordinal", sa.Integer(), nullable=False, server_default="0"),
    )

    # --- validation_runs ---------------------------------------------------
    op.create_table(
        "validation_runs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("template_id", pg.UUID(as_uuid=True), sa.ForeignKey("validation_templates.id"), nullable=True),
        sa.Column("job_id", pg.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="CREATED"),
        sa.Column("sample_size", sa.Integer(), nullable=True),
        sa.Column("total_rows", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("passed_rows", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("warning_rows", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("failed_rows", sa.BigInteger(), nullable=False, server_default="0"),
        sa.Column("quality_score", sa.Numeric(5, 2), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("triggered_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('CREATED', 'QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')",
            name="ck_validation_runs_status",
        ),
    )
    op.create_index(
        "idx_validation_runs_dataset_id_created_at", "validation_runs", ["dataset_id", sa.text("created_at DESC")]
    )
    op.create_index("idx_validation_runs_status", "validation_runs", ["status"])

    # Now that validation_runs exists, add the two FKs that reference it.
    op.create_foreign_key(
        "fk_validation_templates_last_run_id",
        "validation_templates",
        "validation_runs",
        ["last_run_id"],
        ["id"],
    )

    # --- validation_results --------------------------------------------------
    op.create_table(
        "validation_results",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "validation_run_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("validation_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("record_ref", sa.Text(), nullable=False),
        sa.Column("row_index", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(10), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("source_row_hash", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("validation_run_id", "row_index", name="uq_validation_results_run_id_row_index"),
        sa.CheckConstraint("status IN ('PASSED', 'WARNING', 'FAILED')", name="ck_validation_results_status"),
    )
    op.create_index("idx_validation_results_run_status", "validation_results", ["validation_run_id", "status"])
    op.create_index("idx_validation_results_record_ref", "validation_results", ["validation_run_id", "record_ref"])

    # --- validation_failures --------------------------------------------------
    op.create_table(
        "validation_failures",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "validation_result_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("validation_results.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "validation_run_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("validation_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("rule_assignment_id", pg.UUID(as_uuid=True), sa.ForeignKey("rule_assignments.id"), nullable=False),
        sa.Column("column_id", pg.UUID(as_uuid=True), sa.ForeignKey("columns.id"), nullable=True),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("failed_value", sa.Text(), nullable=True),
        sa.Column("expected_value", sa.Text(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint(
            "severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW')", name="ck_validation_failures_severity"
        ),
    )
    op.create_index("idx_validation_failures_run_id", "validation_failures", ["validation_run_id"])
    op.create_index("idx_validation_failures_column_id", "validation_failures", ["column_id"])
    op.create_index("idx_validation_failures_rule_assignment_id", "validation_failures", ["rule_assignment_id"])
    op.create_index("idx_validation_failures_severity", "validation_failures", ["validation_run_id", "severity"])

    # --- validation_metrics --------------------------------------------------
    op.create_table(
        "validation_metrics",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "validation_run_id",
            pg.UUID(as_uuid=True),
            sa.ForeignKey("validation_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("metric_name", sa.String(100), nullable=False),
        sa.Column("metric_group", sa.String(255), nullable=True),
        sa.Column("metric_value", sa.Numeric(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint(
            "validation_run_id", "metric_name", "metric_group", name="uq_validation_metrics_run_name_group"
        ),
    )
    op.create_index("idx_validation_metrics_run_id", "validation_metrics", ["validation_run_id"])

    # --- seed validation.run and link into every role -----------------------
    connection = op.get_bind()

    permission_id = connection.execute(
        table("permissions", column("code", String), column("category", String))
        .insert()
        .values(code=PERMISSION_CODE, category=PERMISSION_CATEGORY)
        .returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLE_NAMES_RECEIVING_NEW_PERMISSION
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_id, "permission_id": permission_id} for role_id in role_ids.values()],
    )


def downgrade() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = :code)"
        ),
        {"code": PERMISSION_CODE},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = :code"), {"code": PERMISSION_CODE})

    op.drop_table("validation_metrics")

    op.drop_index("idx_validation_failures_severity", table_name="validation_failures")
    op.drop_index("idx_validation_failures_rule_assignment_id", table_name="validation_failures")
    op.drop_index("idx_validation_failures_column_id", table_name="validation_failures")
    op.drop_index("idx_validation_failures_run_id", table_name="validation_failures")
    op.drop_table("validation_failures")

    op.drop_index("idx_validation_results_record_ref", table_name="validation_results")
    op.drop_index("idx_validation_results_run_status", table_name="validation_results")
    op.drop_table("validation_results")

    op.drop_constraint("fk_validation_templates_last_run_id", "validation_templates", type_="foreignkey")

    op.drop_index("idx_validation_runs_status", table_name="validation_runs")
    op.drop_index("idx_validation_runs_dataset_id_created_at", table_name="validation_runs")
    op.drop_table("validation_runs")

    op.drop_table("rule_assignment_columns")

    op.drop_index("idx_rule_assignments_scope", table_name="rule_assignments")
    op.drop_index("idx_rule_assignments_template_id", table_name="rule_assignments")
    op.drop_index("idx_rule_assignments_dataset_id", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_cross_with_template", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_cross_no_template", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_dataset_with_template", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_dataset_no_template", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_single_with_template", table_name="rule_assignments")
    op.drop_index("uq_rule_assignments_single_no_template", table_name="rule_assignments")
    op.drop_table("rule_assignments")

    op.drop_table("validation_templates")

    op.drop_index("uq_rule_versions_current", table_name="rule_versions")
    op.drop_index("idx_rule_versions_rule_id", table_name="rule_versions")
    op.drop_table("rule_versions")

    op.drop_index("idx_rules_origin", table_name="rules")
    op.drop_index("idx_rules_status", table_name="rules")
    op.drop_table("rules")
