"""Phase 6: review + corrections foundation (4 tables)

Revision ID: 0010_phase6_review_corrections
Revises: 0009_phase5_validation_base
Create Date: 2026-08-21

Creates, exactly per the frozen Database Design v2 field lists (Section 6
REVIEW): review_runs, issues, correction_suggestions, corrections.

AUTHORIZED DEVIATION (the only one in this migration): the frozen design
specifies correction_suggestions.ai_suggestion_id as UUID with a FOREIGN KEY
REFERENCES ai_suggestions(id). Confirmed via live inspection before writing
this migration that the `ai_suggestions` table does not exist yet — it
belongs to the AI Orchestrator module, out of scope for this phase.
Postgres cannot create a FK against a nonexistent table, so
ai_suggestion_id is created here as a plain nullable UUID column with NO
FOREIGN KEY. The frozen CHECK constraint
  (source = 'AI') = (ai_suggestion_id IS NOT NULL)
is still created and enforced exactly as specified — it does not depend on
the FK. Whichever future migration creates ai_suggestions MUST add:
  ALTER TABLE correction_suggestions ADD CONSTRAINT
    fk_correction_suggestions_ai_suggestion_id
    FOREIGN KEY (ai_suggestion_id) REFERENCES ai_suggestions(id);

No change to jobs.job_type or any other existing table: Phase 6 is fully
synchronous (no Celery task, no jobs table involvement anywhere in this
phase), per the approved plan.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0009.

Also seeds two new permission codes, review.read and review.edit (category:
review), and links both into every one of the 5 roles seeded by migration
0006 — same reasoning as every prior phase's permission migration: the
frozen role hierarchy (reviewer approximately equals analyst; approver is a
superset of analyst; publisher is a superset of approver, which is a
superset of analyst) means every role inherits both. No admin-only
restriction on review.edit (unlike rules.manage's elevated-risk exclusion
in Phase 5's design discussion) — the Phase 6 correction generators are
fixed, deterministic code, not user-authored expressions, so there is no
comparable elevated-risk surface here.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0010_phase6_review_corrections"
down_revision: Union[str, Sequence[str], None] = "0009_phase5_validation_base"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PERMISSION_CODES = [("review.read", "review"), ("review.edit", "review")]
ROLE_NAMES_RECEIVING_NEW_PERMISSIONS = ["administrator", "analyst", "reviewer", "approver", "publisher"]


def upgrade() -> None:
    # --- review_runs --------------------------------------------------------
    op.create_table(
        "review_runs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("validation_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("validation_runs.id"), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("status", sa.String(20), nullable=False, server_default="DRAFT"),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'IN_REVIEW', 'READY_FOR_APPROVAL', 'ARCHIVED')", name="ck_review_runs_status"
        ),
    )
    op.create_index("idx_review_runs_validation_run_id", "review_runs", ["validation_run_id"])
    op.create_index("idx_review_runs_status", "review_runs", ["status"])

    # --- issues --------------------------------------------------------------
    op.create_table(
        "issues",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "review_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("review_runs.id", ondelete="CASCADE"), nullable=False
        ),
        sa.Column("validation_failure_id", pg.UUID(as_uuid=True), sa.ForeignKey("validation_failures.id"), nullable=False),
        sa.Column("column_id", pg.UUID(as_uuid=True), sa.ForeignKey("columns.id"), nullable=True),
        sa.Column("record_ref", sa.Text(), nullable=False),
        sa.Column("row_index", sa.BigInteger(), nullable=False),
        sa.Column("original_value", sa.Text(), nullable=True),
        sa.Column("severity", sa.String(20), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("assigned_reviewer_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint(
            "review_run_id", "validation_failure_id", name="uq_issues_review_run_id_validation_failure_id"
        ),
        sa.CheckConstraint("status IN ('PENDING', 'IN_PROGRESS', 'RESOLVED', 'SKIPPED')", name="ck_issues_status"),
    )
    op.create_index("idx_issues_review_run_status", "issues", ["review_run_id", "status"])
    op.create_index("idx_issues_column_id", "issues", ["column_id"])
    op.create_index("idx_issues_record_ref", "issues", ["record_ref"])

    # --- correction_suggestions ------------------------------------------------
    op.create_table(
        "correction_suggestions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("issue_id", pg.UUID(as_uuid=True), sa.ForeignKey("issues.id", ondelete="CASCADE"), nullable=False),
        sa.Column("source", sa.String(20), nullable=False),
        # No FK — see module docstring above (ai_suggestions doesn't exist yet).
        sa.Column("ai_suggestion_id", pg.UUID(as_uuid=True), nullable=True),
        sa.Column("suggested_value", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=False),
        sa.Column("fix_type", sa.String(50), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("is_selected", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("selected_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("selected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint("source IN ('RULE_BASED', 'AI', 'HUMAN')", name="ck_correction_suggestions_source"),
        sa.CheckConstraint(
            "(source = 'AI') = (ai_suggestion_id IS NOT NULL)", name="ck_correction_suggestions_ai_suggestion_id_shape"
        ),
    )
    op.create_index(
        "uq_correction_suggestions_issue_selected",
        "correction_suggestions",
        ["issue_id"],
        unique=True,
        postgresql_where=sa.text("is_selected"),
    )
    op.create_index("idx_correction_suggestions_issue_id", "correction_suggestions", ["issue_id"])

    # --- corrections --------------------------------------------------------
    op.create_table(
        "corrections",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("issue_id", pg.UUID(as_uuid=True), sa.ForeignKey("issues.id", ondelete="CASCADE"), nullable=False),
        sa.Column(
            "correction_suggestion_id", pg.UUID(as_uuid=True), sa.ForeignKey("correction_suggestions.id"), nullable=True
        ),
        sa.Column("final_value", sa.Text(), nullable=True),
        sa.Column("value_source", sa.String(20), nullable=True),
        sa.Column("status", sa.String(20), nullable=False),
        sa.Column("decided_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("issue_id", name="uq_corrections_issue_id"),
        sa.CheckConstraint("value_source IS NULL OR value_source IN ('RULE_BASED', 'AI', 'HUMAN')", name="ck_corrections_value_source"),
        sa.CheckConstraint(
            "status IN ('SUGGESTED', 'ACCEPTED', 'EDITED', 'REJECTED', 'SKIPPED')", name="ck_corrections_status"
        ),
    )
    op.create_index("idx_corrections_status", "corrections", ["status"])

    # --- seed review.read / review.edit and link into every role -----------------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    permission_ids = {}
    for code, category in PERMISSION_CODES:
        permission_ids[code] = connection.execute(
            permissions_table.insert().values(code=code, category=category).returning(column("id"))
        ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLE_NAMES_RECEIVING_NEW_PERMISSIONS
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [
            {"role_id": role_id, "permission_id": permission_id}
            for permission_id in permission_ids.values()
            for role_id in role_ids.values()
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()

    codes = [c for c, _ in PERMISSION_CODES]
    connection.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": codes},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})

    op.drop_index("idx_corrections_status", table_name="corrections")
    op.drop_table("corrections")

    op.drop_index("idx_correction_suggestions_issue_id", table_name="correction_suggestions")
    op.drop_index("uq_correction_suggestions_issue_selected", table_name="correction_suggestions")
    op.drop_table("correction_suggestions")

    op.drop_index("idx_issues_record_ref", table_name="issues")
    op.drop_index("idx_issues_column_id", table_name="issues")
    op.drop_index("idx_issues_review_run_status", table_name="issues")
    op.drop_table("issues")

    op.drop_index("idx_review_runs_status", table_name="review_runs")
    op.drop_index("idx_review_runs_validation_run_id", table_name="review_runs")
    op.drop_table("review_runs")
