"""Phase 7: approval foundation (3 tables)

Revision ID: 0011_phase7_approval
Revises: 0010_phase6_review_corrections
Create Date: 2026-08-22

Creates, exactly per the frozen Database Design v2 field lists (Section 7
APPROVAL): approval_requests, approval_decisions, approval_decision_issues.

No amendments beyond exactly what's specified. No approval-scope table is
created — resolved-issue scope is computed at query time from
issues/corrections/approval_decision_issues, per the Phase 7 design's
explicit rejection of persisting a scope list.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0010.

Also seeds two new permission codes, approval.read and approval.decide
(category: approval). Unlike every prior phase's permission seeding, this
is NOT a uniform grant to all 5 roles: approval.read goes to all 5 (same
as every previous "everyone inherits" pattern), but approval.decide goes
only to administrator, approver, and publisher — analyst and reviewer get
read-only. This is the first genuine divergence between analyst and
approver in this project's permission history: per the frozen Backend
Technical Design's own stated definition, approver = analyst's permission
set + approval.decide.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0011_phase7_approval"
down_revision: Union[str, Sequence[str], None] = "0010_phase6_review_corrections"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLES_RECEIVING_APPROVAL_READ = ["administrator", "analyst", "reviewer", "approver", "publisher"]
ROLES_RECEIVING_APPROVAL_DECIDE = ["administrator", "approver", "publisher"]


def upgrade() -> None:
    # --- approval_requests --------------------------------------------------
    op.create_table(
        "approval_requests",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("review_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("review_runs.id"), nullable=False),
        sa.Column("status", sa.String(20), nullable=False, server_default="PENDING"),
        sa.Column("affected_issue_count", sa.Integer(), nullable=False),
        sa.Column("affected_record_count", sa.Integer(), nullable=False),
        sa.Column("requested_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED', 'PARTIALLY_APPROVED')", name="ck_approval_requests_status"
        ),
    )
    op.create_index("idx_approval_requests_review_run_id", "approval_requests", ["review_run_id"])
    op.create_index("idx_approval_requests_status", "approval_requests", ["status"])

    # --- approval_decisions --------------------------------------------------
    op.create_table(
        "approval_decisions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "approval_request_id", pg.UUID(as_uuid=True), sa.ForeignKey("approval_requests.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("decision", sa.String(20), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("decided_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint("decision IN ('APPROVE', 'REJECT')", name="ck_approval_decisions_decision"),
    )
    op.create_index("idx_approval_decisions_request_id", "approval_decisions", ["approval_request_id"])

    # --- approval_decision_issues ------------------------------------------
    op.create_table(
        "approval_decision_issues",
        sa.Column(
            "approval_decision_id", pg.UUID(as_uuid=True), sa.ForeignKey("approval_decisions.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        sa.Column("issue_id", pg.UUID(as_uuid=True), sa.ForeignKey("issues.id"), primary_key=True),
    )

    # --- seed approval.read / approval.decide and link into roles -----------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    read_permission_id = connection.execute(
        permissions_table.insert().values(code="approval.read", category="approval").returning(column("id"))
    ).scalar_one()
    decide_permission_id = connection.execute(
        permissions_table.insert().values(code="approval.decide", category="approval").returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLES_RECEIVING_APPROVAL_READ
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_ids[name], "permission_id": read_permission_id} for name in ROLES_RECEIVING_APPROVAL_READ]
        + [{"role_id": role_ids[name], "permission_id": decide_permission_id} for name in ROLES_RECEIVING_APPROVAL_DECIDE],
    )


def downgrade() -> None:
    connection = op.get_bind()

    codes = ["approval.read", "approval.decide"]
    connection.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": codes},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})

    op.drop_table("approval_decision_issues")

    op.drop_index("idx_approval_decisions_request_id", table_name="approval_decisions")
    op.drop_table("approval_decisions")

    op.drop_index("idx_approval_requests_status", table_name="approval_requests")
    op.drop_index("idx_approval_requests_review_run_id", table_name="approval_requests")
    op.drop_table("approval_requests")
