"""Phase 8: staging foundation (2 tables)

Revision ID: 0012_phase8_staging_foundation
Revises: 0011_phase7_approval
Create Date: 2026-08-22

Creates, exactly per the frozen Database Design v2 field lists and this
phase's locked spec: staging_runs, staging_records.

No amendments beyond exactly what's specified. staging_runs.job_id exists
(per the frozen schema) but remains NULL always in this phase's output —
Phase 8 is fully synchronous by locked design decision, no Celery task, no
jobs table involvement.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0011.

Also seeds two new permission codes, staging.create and staging.read
(category: staging). Non-uniform split (same pattern as Phase 7's
approval.read/approval.decide): staging.read goes to all 5 roles;
staging.create goes only to administrator, approver, and publisher —
analyst and reviewer get read-only, mirroring the approval.decide split
exactly.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0012_phase8_staging_foundation"
down_revision: Union[str, Sequence[str], None] = "0011_phase7_approval"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLES_RECEIVING_STAGING_READ = ["administrator", "analyst", "reviewer", "approver", "publisher"]
ROLES_RECEIVING_STAGING_CREATE = ["administrator", "approver", "publisher"]


def upgrade() -> None:
    # --- staging_runs --------------------------------------------------------
    op.create_table(
        "staging_runs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("review_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("review_runs.id"), nullable=False),
        sa.Column("dataset_id", pg.UUID(as_uuid=True), sa.ForeignKey("datasets.id"), nullable=False),
        sa.Column("job_id", pg.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=True),
        sa.Column("attempt_number", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("status", sa.String(15), nullable=False, server_default="NOT_STARTED"),
        sa.Column("record_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("field_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("has_source_drift", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("review_run_id", "attempt_number", name="uq_staging_runs_review_run_id_attempt_number"),
        sa.CheckConstraint("status IN ('NOT_STARTED', 'BUILDING', 'READY', 'FAILED')", name="ck_staging_runs_status"),
    )
    op.create_index("idx_staging_runs_dataset_id", "staging_runs", ["dataset_id"])
    op.create_index("idx_staging_runs_status", "staging_runs", ["status"])
    op.create_index(
        "idx_staging_runs_review_run_id", "staging_runs", ["review_run_id", sa.text("attempt_number DESC")]
    )
    # Exactly one is_current=true row per review_run_id.
    op.create_index(
        "uq_staging_runs_current",
        "staging_runs",
        ["review_run_id"],
        unique=True,
        postgresql_where=sa.text("is_current"),
    )

    # --- staging_records --------------------------------------------------
    op.create_table(
        "staging_records",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "staging_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("staging_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("record_ref", sa.Text(), nullable=False),
        sa.Column("row_snapshot", pg.JSONB(), nullable=False),
        sa.Column("corrected_fields", pg.JSONB(), nullable=False, server_default="[]"),
        sa.Column("source_row_hash_at_validation", sa.Text(), nullable=False),
        sa.Column("source_row_hash_at_staging", sa.Text(), nullable=True),
        sa.Column("source_drift_status", sa.String(20), nullable=False, server_default="UNCHANGED"),
        sa.Column("source_drift_fields", pg.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint("staging_run_id", "record_ref", name="uq_staging_records_staging_run_id_record_ref"),
        sa.CheckConstraint(
            "source_drift_status IN ('UNCHANGED', 'VALUE_CHANGED', 'RECORD_NOT_FOUND')",
            name="ck_staging_records_source_drift_status",
        ),
    )
    op.create_index("idx_staging_records_staging_run_id", "staging_records", ["staging_run_id"])
    op.create_index(
        "idx_staging_records_drift",
        "staging_records",
        ["staging_run_id", "source_drift_status"],
        postgresql_where=sa.text("source_drift_status <> 'UNCHANGED'"),
    )

    # --- seed staging.create / staging.read and link into roles -----------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    read_permission_id = connection.execute(
        permissions_table.insert().values(code="staging.read", category="staging").returning(column("id"))
    ).scalar_one()
    create_permission_id = connection.execute(
        permissions_table.insert().values(code="staging.create", category="staging").returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLES_RECEIVING_STAGING_READ
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_ids[name], "permission_id": read_permission_id} for name in ROLES_RECEIVING_STAGING_READ]
        + [
            {"role_id": role_ids[name], "permission_id": create_permission_id}
            for name in ROLES_RECEIVING_STAGING_CREATE
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()

    codes = ["staging.read", "staging.create"]
    connection.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": codes},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})

    op.drop_index("idx_staging_records_drift", table_name="staging_records")
    op.drop_index("idx_staging_records_staging_run_id", table_name="staging_records")
    op.drop_table("staging_records")

    op.drop_index("uq_staging_runs_current", table_name="staging_runs")
    op.drop_index("idx_staging_runs_review_run_id", table_name="staging_runs")
    op.drop_index("idx_staging_runs_status", table_name="staging_runs")
    op.drop_index("idx_staging_runs_dataset_id", table_name="staging_runs")
    op.drop_table("staging_runs")
