"""Phase 9: publishing foundation (1 table + approved job_id amendment)

Revision ID: 0013_phase9_publish_foundation
Revises: 0012_phase8_staging_foundation
Create Date: 2026-08-26

Creates publish_runs exactly per the frozen Database Design v2 field list,
plus the ONE authorized amendment for this phase: publish_runs.job_id UUID
NULL FK jobs(id), matching the exact pattern already used by
profile_runs.job_id / validation_runs.job_id / staging_runs.job_id. No
other schema change is made — 'PUBLISH' has been a valid jobs.job_type
value since the original frozen schema (confirmed live via pg_constraint
before writing this migration: ck_jobs_job_type already includes
'PUBLISH'), so no jobs table change is needed either.

No attempt_number/is_current columns — a deliberate, approved asymmetry
with staging_runs (locked decision 5): retries after FAILED are
independent new rows, there is no "current publish attempt" concept.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0012.

Also seeds two new permission codes, publish.execute and publish.read
(category: publish). Non-uniform split, same pattern as Phase 7/8:
publish.read goes to all 5 roles; publish.execute goes only to
administrator and publisher. Notably, approver does NOT get publish.execute
— the first phase in this project where a role does not simply inherit the
next stage's capability (approver can approve and stage, but cannot
publish unless also a publisher).
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0013_phase9_publish_foundation"
down_revision: Union[str, Sequence[str], None] = "0012_phase8_staging_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLES_RECEIVING_PUBLISH_READ = ["administrator", "analyst", "reviewer", "approver", "publisher"]
ROLES_RECEIVING_PUBLISH_EXECUTE = ["administrator", "publisher"]


def upgrade() -> None:
    # --- publish_runs --------------------------------------------------------
    op.create_table(
        "publish_runs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("staging_run_id", pg.UUID(as_uuid=True), sa.ForeignKey("staging_runs.id"), nullable=False),
        # Approved amendment (locked decision 3) — matches profile_runs.job_id /
        # validation_runs.job_id / staging_runs.job_id exactly.
        sa.Column("job_id", pg.UUID(as_uuid=True), sa.ForeignKey("jobs.id"), nullable=True),
        sa.Column("status", sa.String(15), nullable=False, server_default="PENDING"),
        sa.Column("target_type", sa.String(30), nullable=False),
        sa.Column("target_reference", sa.Text(), nullable=True),
        sa.Column("published_record_count", sa.Integer(), nullable=True),
        sa.Column("drift_acknowledged", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("drift_acknowledged_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("drift_acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("published_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('PENDING', 'PUBLISHING', 'PUBLISHED', 'FAILED')", name="ck_publish_runs_status"),
        sa.CheckConstraint(
            "target_type IN ('WAREHOUSE_TABLE', 'SOURCE_TABLE', 'FILE_EXPORT', 'API')",
            name="ck_publish_runs_target_type",
        ),
    )
    op.create_index("idx_publish_runs_staging_run_id", "publish_runs", ["staging_run_id"])
    op.create_index("idx_publish_runs_status", "publish_runs", ["status"])

    # --- seed publish.execute / publish.read and link into roles -----------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    read_permission_id = connection.execute(
        permissions_table.insert().values(code="publish.read", category="publish").returning(column("id"))
    ).scalar_one()
    execute_permission_id = connection.execute(
        permissions_table.insert().values(code="publish.execute", category="publish").returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLES_RECEIVING_PUBLISH_READ
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_ids[name], "permission_id": read_permission_id} for name in ROLES_RECEIVING_PUBLISH_READ]
        + [
            {"role_id": role_ids[name], "permission_id": execute_permission_id}
            for name in ROLES_RECEIVING_PUBLISH_EXECUTE
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()

    codes = ["publish.read", "publish.execute"]
    connection.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": codes},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})

    op.drop_index("idx_publish_runs_status", table_name="publish_runs")
    op.drop_index("idx_publish_runs_staging_run_id", table_name="publish_runs")
    op.drop_table("publish_runs")
