"""Phase 10: lineage foundation (1 table, frozen shape, no mutation surface)

Revision ID: 0014_phase10_lineage_foundation
Revises: 0013_phase9_publish_foundation
Create Date: 2026-08-26

Creates lineage_records exactly per the frozen shape: id, parent_entity_type,
parent_entity_id, child_entity_type, child_entity_id, relationship_type,
created_at. No new column, no new constraint may ever be added to this
table — any future need must be met with a new relationship_type/
entity_type value, never a schema change.

entity_type and relationship_type columns are DELIBERATELY left as plain
VARCHAR(30) with NO CHECK constraint, unlike every enum-shaped column in
prior phases (e.g. publish_runs.status/target_type). This is intentional:
Decision 2 (Phase 10 design) extends the entity_type vocabulary with
PROFILE_RUN and REVIEW_RUN, and the relationship_type vocabulary with
PROFILED_BY, VALIDATED_BY, DERIVED_FROM, CORRECTED_BY, APPROVED_BY,
STAGED_INTO, PUBLISHED_TO — all usable immediately, with no migration
needed to add further values later. Existing entity_type values reused
here (CONNECTION, SCHEMA, DATASET, COLUMN, ISSUE, CORRECTION,
APPROVAL_REQUEST, STAGING_RUN, PUBLISH_RUN, DATA_SOURCE) already exist as
free-text values elsewhere (e.g. audit_events.entity_type, also
unconstrained Text) — this is consistent with, not a new pattern versus,
that existing convention.

Idempotency is enforced entirely by the UNIQUE constraint below (INSERT
... ON CONFLICT DO NOTHING at the application layer, in
LineageService.record_edge/record_edges_bulk) — no additional locking or
pre-check, per the approved design.

Also seeds permission code lineage.read (category: lineage), linked to
all five roles uniformly (no lineage.manage/lineage.build — this project
has no lineage mutation endpoint of any kind).

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0013.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0014_phase10_lineage_foundation"
down_revision: Union[str, Sequence[str], None] = "0013_phase9_publish_foundation"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLES_RECEIVING_LINEAGE_READ = ["administrator", "analyst", "reviewer", "approver", "publisher"]


def upgrade() -> None:
    # --- lineage_records -----------------------------------------------------
    op.create_table(
        "lineage_records",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("parent_entity_type", sa.String(30), nullable=False),
        sa.Column("parent_entity_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("child_entity_type", sa.String(30), nullable=False),
        sa.Column("child_entity_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("relationship_type", sa.String(30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint(
            "parent_entity_type", "parent_entity_id", "child_entity_type", "child_entity_id", "relationship_type",
            name="uq_lineage_records_edge",
        ),
    )
    op.create_index("idx_lineage_parent", "lineage_records", ["parent_entity_type", "parent_entity_id"])
    op.create_index("idx_lineage_child", "lineage_records", ["child_entity_type", "child_entity_id"])

    # --- seed lineage.read and link into all 5 roles ------------------------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    read_permission_id = connection.execute(
        permissions_table.insert().values(code="lineage.read", category="lineage").returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLES_RECEIVING_LINEAGE_READ
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_ids[name], "permission_id": read_permission_id} for name in ROLES_RECEIVING_LINEAGE_READ],
    )


def downgrade() -> None:
    connection = op.get_bind()

    connection.execute(
        sa.text(
            "DELETE FROM role_permissions WHERE permission_id IN "
            "(SELECT id FROM permissions WHERE code = 'lineage.read')"
        )
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = 'lineage.read'"))

    op.drop_index("idx_lineage_child", table_name="lineage_records")
    op.drop_index("idx_lineage_parent", table_name="lineage_records")
    op.drop_table("lineage_records")
