"""Phase 12: AI Orchestrator foundation (5 tables, 2 deferred FK
attachments, 1 jobs.job_type CHECK amendment, RBAC seed)

Revision ID: 0016_phase12_ai_foundation
Revises: 0015_phase11_reports_rbac
Create Date: 2026-08-27

Creates ai_prompt_versions, ai_conversations, ai_messages, ai_suggestions,
ai_usage_logs exactly per the frozen Database Design v2 Section 11 field
list (locked Phase 12 decisions). No business prompt-template rows are
seeded here — that is a deliberately separate, future, controlled seed
step (a standalone script, mirroring scripts/create_admin_user.py's
convention), not part of this migration.

Attaches the two FKs deferred since Phase 3/6 (confirmed live via
pg_constraint before writing this migration: neither FK existed):
  correction_suggestions.ai_suggestion_id -> ai_suggestions.id
    (constraint name fk_correction_suggestions_ai_suggestion_id, exactly
    as anticipated in app/db/models/review.py's code comment since Phase 6)
  columns.semantic_category_ai_suggestion_id -> ai_suggestions.id
    (constraint name fk_columns_semantic_category_ai_suggestion_id, per
    the locked Phase 12 decision — no specific name was anticipated in
    the Phase 3 code comment, so this migration establishes it)
Neither existing column definition nor either table's existing CHECK
constraints are touched — additive FK attachment only.

Amends ck_jobs_job_type to add 'AI_SUGGESTION' (the first amendment of an
existing CHECK's value list in this project's history — every prior
phase's job_type value was already present in the original list, e.g.
'PUBLISH' confirmed already valid before Phase 9). Postgres has no ALTER
CHECK; this drops and recreates the constraint. No existing job_type
value is touched.

Seeds ai.chat and ai.suggest (category: ai), linked to administrator,
analyst, approver, and reviewer — NOT publisher (AI is an advisory data-
quality/review capability, not a publishing capability; this is the
second phase in this project, after Phase 9's publish.execute/approver
split, where a role is deliberately excluded from a new permission). No
ai.approve permission exists anywhere — ai.chat/ai.suggest never grant
approval authority; approval.read, approval.decide, staging.create, and
publish.execute remain the sole authoritative permissions for their
respective actions, and AI never bypasses them.

Hand-written rather than autogenerated, matching the discipline of
migrations 0002-0015.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy import String
from sqlalchemy import column, table
from sqlalchemy.dialects import postgresql as pg

from alembic import op

revision: str = "0016_phase12_ai_foundation"
down_revision: Union[str, Sequence[str], None] = "0015_phase11_reports_rbac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


ROLES_RECEIVING_AI_PERMISSIONS = ["administrator", "analyst", "approver", "reviewer"]

_ORIGINAL_JOB_TYPE_CHECK = (
    "job_type IN ('PROFILE_RUN', 'VALIDATION_RUN', 'STAGING_BUILD', 'PUBLISH', 'EXPORT', 'DISCOVERY_RUN')"
)
_AMENDED_JOB_TYPE_CHECK = (
    "job_type IN ('PROFILE_RUN', 'VALIDATION_RUN', 'STAGING_BUILD', 'PUBLISH', 'EXPORT', 'DISCOVERY_RUN', "
    "'AI_SUGGESTION')"
)


def upgrade() -> None:
    # --- ai_prompt_versions ---------------------------------------------------
    op.create_table(
        "ai_prompt_versions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("prompt_key", sa.String(100), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("default_model", sa.String(100), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("created_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.UniqueConstraint(
            "prompt_key", "version_number", name="uq_ai_prompt_versions_prompt_key_version_number"
        ),
    )
    op.create_index(
        "idx_ai_prompt_versions_active", "ai_prompt_versions", ["prompt_key"],
        postgresql_where=sa.text("is_active"),
    )

    # --- ai_conversations ------------------------------------------------------
    op.create_table(
        "ai_conversations",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("context", pg.JSONB(), nullable=True),
        sa.Column("status", sa.String(15), nullable=False, server_default="ACTIVE"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('ACTIVE', 'CLOSED')", name="ck_ai_conversations_status"),
    )
    op.create_index("idx_ai_conversations_user_id", "ai_conversations", ["user_id", sa.text("updated_at DESC")])

    # --- ai_messages -------------------------------------------------------
    op.create_table(
        "ai_messages",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column(
            "conversation_id", pg.UUID(as_uuid=True),
            sa.ForeignKey("ai_conversations.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("role", sa.String(15), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tool_calls", pg.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint("role IN ('USER', 'ASSISTANT', 'SYSTEM_NOTE')", name="ck_ai_messages_role"),
    )
    op.create_index("idx_ai_messages_conversation_id", "ai_messages", ["conversation_id", "created_at"])

    # --- ai_suggestions ------------------------------------------------------
    op.create_table(
        "ai_suggestions",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("suggestion_type", sa.String(30), nullable=False),
        sa.Column("source_context_type", sa.String(30), nullable=False),
        sa.Column("source_context_id", pg.UUID(as_uuid=True), nullable=False),
        sa.Column("content", pg.JSONB(), nullable=False),
        sa.Column("confidence", sa.Numeric(4, 3), nullable=True),
        sa.Column("provider", sa.String(50), nullable=False),
        sa.Column("model", sa.String(100), nullable=False),
        sa.Column(
            "prompt_version_id", pg.UUID(as_uuid=True), sa.ForeignKey("ai_prompt_versions.id"), nullable=False
        ),
        sa.Column("conversation_id", pg.UUID(as_uuid=True), sa.ForeignKey("ai_conversations.id"), nullable=True),
        sa.Column("requested_by", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("status", sa.String(15), nullable=False, server_default="PROPOSED"),
        # Carries {"input_context_hash": "<sha256 hex digest>"} — canonical
        # JSON serialization hashed with hashlib.sha256, never Python's
        # built-in hash() (not reproducible across processes).
        sa.Column("response_metadata", pg.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.CheckConstraint(
            "suggestion_type IN ('CORRECTION', 'RULE_RECOMMENDATION', 'SEMANTIC_CATEGORY', 'EXPLANATION', "
            "'RUN_SUMMARY', 'CLUSTER', 'PRIORITIZATION')",
            name="ck_ai_suggestions_suggestion_type",
        ),
        sa.CheckConstraint(
            "source_context_type IN ('ISSUE', 'COLUMN', 'DATASET', 'VALIDATION_RUN', 'REVIEW_RUN')",
            name="ck_ai_suggestions_source_context_type",
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED', 'ACCEPTED', 'REJECTED', 'EXPIRED')", name="ck_ai_suggestions_status"
        ),
    )
    op.create_index("idx_ai_suggestions_context", "ai_suggestions", ["source_context_type", "source_context_id"])
    op.create_index("idx_ai_suggestions_type_status", "ai_suggestions", ["suggestion_type", "status"])

    # --- ai_usage_logs -------------------------------------------------------
    op.create_table(
        "ai_usage_logs",
        sa.Column("id", pg.UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("conversation_id", pg.UUID(as_uuid=True), sa.ForeignKey("ai_conversations.id"), nullable=True),
        sa.Column("ai_suggestion_id", pg.UUID(as_uuid=True), sa.ForeignKey("ai_suggestions.id"), nullable=True),
        sa.Column("user_id", pg.UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=False),
        sa.Column("provider", sa.String(50), nullable=False),
        sa.Column("model", sa.String(100), nullable=False),
        sa.Column(
            "prompt_version_id", pg.UUID(as_uuid=True), sa.ForeignKey("ai_prompt_versions.id"), nullable=True
        ),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cost_estimate", sa.Numeric(10, 4), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
    )
    op.create_index("idx_ai_usage_logs_user_id_created_at", "ai_usage_logs", ["user_id", "created_at"])
    op.create_index("idx_ai_usage_logs_created_at", "ai_usage_logs", ["created_at"])

    # --- deferred FK attachments (additive only) ------------------------------
    op.create_foreign_key(
        "fk_correction_suggestions_ai_suggestion_id", "correction_suggestions", "ai_suggestions",
        ["ai_suggestion_id"], ["id"],
    )
    op.create_foreign_key(
        "fk_columns_semantic_category_ai_suggestion_id", "columns", "ai_suggestions",
        ["semantic_category_ai_suggestion_id"], ["id"],
    )

    # --- jobs.job_type CHECK amendment (additive value only) -----------------
    op.drop_constraint("ck_jobs_job_type", "jobs", type_="check")
    op.create_check_constraint("ck_jobs_job_type", "jobs", _AMENDED_JOB_TYPE_CHECK)

    # --- seed ai.chat / ai.suggest and link into roles ------------------------
    connection = op.get_bind()

    permissions_table = table("permissions", column("code", String), column("category", String))
    chat_permission_id = connection.execute(
        permissions_table.insert().values(code="ai.chat", category="ai").returning(column("id"))
    ).scalar_one()
    suggest_permission_id = connection.execute(
        permissions_table.insert().values(code="ai.suggest", category="ai").returning(column("id"))
    ).scalar_one()

    role_ids = {
        name: connection.execute(sa.text("SELECT id FROM roles WHERE name = :name"), {"name": name}).scalar_one()
        for name in ROLES_RECEIVING_AI_PERMISSIONS
    }

    role_permissions_table = table("role_permissions", column("role_id"), column("permission_id"))
    op.bulk_insert(
        role_permissions_table,
        [{"role_id": role_ids[name], "permission_id": chat_permission_id} for name in ROLES_RECEIVING_AI_PERMISSIONS]
        + [
            {"role_id": role_ids[name], "permission_id": suggest_permission_id}
            for name in ROLES_RECEIVING_AI_PERMISSIONS
        ],
    )


def downgrade() -> None:
    connection = op.get_bind()

    # --- RBAC seed ---------------------------------------------------------
    codes = ["ai.chat", "ai.suggest"]
    connection.execute(
        sa.text("DELETE FROM role_permissions WHERE permission_id IN (SELECT id FROM permissions WHERE code = ANY(:codes))"),
        {"codes": codes},
    )
    connection.execute(sa.text("DELETE FROM permissions WHERE code = ANY(:codes)"), {"codes": codes})

    # --- jobs.job_type CHECK amendment --------------------------------------
    op.drop_constraint("ck_jobs_job_type", "jobs", type_="check")
    op.create_check_constraint("ck_jobs_job_type", "jobs", _ORIGINAL_JOB_TYPE_CHECK)

    # --- deferred FK attachments ---------------------------------------------
    op.drop_constraint("fk_columns_semantic_category_ai_suggestion_id", "columns", type_="foreignkey")
    op.drop_constraint("fk_correction_suggestions_ai_suggestion_id", "correction_suggestions", type_="foreignkey")

    # --- five AI tables (children before parents) -----------------------------
    op.drop_index("idx_ai_usage_logs_created_at", table_name="ai_usage_logs")
    op.drop_index("idx_ai_usage_logs_user_id_created_at", table_name="ai_usage_logs")
    op.drop_table("ai_usage_logs")

    op.drop_index("idx_ai_suggestions_type_status", table_name="ai_suggestions")
    op.drop_index("idx_ai_suggestions_context", table_name="ai_suggestions")
    op.drop_table("ai_suggestions")

    op.drop_index("idx_ai_messages_conversation_id", table_name="ai_messages")
    op.drop_table("ai_messages")

    op.drop_index("idx_ai_conversations_user_id", table_name="ai_conversations")
    op.drop_table("ai_conversations")

    op.drop_index("idx_ai_prompt_versions_active", table_name="ai_prompt_versions")
    op.drop_table("ai_prompt_versions")
